# Generated by Django 6.0.5 on 2026-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_duration_minutes', models.IntegerField(default=60)),
                ('marks_per_correct', models.IntegerField(default=4)),
                ('negative_marking_enabled', models.BooleanField(default=True)),
                ('negative_marks', models.IntegerField(default=1)),
                ('allow_unlimited_time', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('total_questions', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('pass_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mock_tests',
                'ordering': ['-created_at'],
            },
        ),
    ]
