# Generated by Django 4.2.30 on 2026-05-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='chapter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='passing_marks',
            field=models.FloatField(default=35.0),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='test_type',
            field=models.CharField(blank=True, choices=[('latest', 'Latest Tests'), ('pyq', 'Previous Year Questions'), ('subject', 'Subject Wise'), ('chapter', 'Chapter Wise'), ('full', 'Full Mock Test')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
