# Generated by Django 6.0.5 on 2026-05-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.mocktest'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'question_number')},
        ),
    ]
