# Generated by Django 6.0 on 2026-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('math', 'Mathematics'), ('physics', 'Physics'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
    ]
