# Generated by Django 6.0.5 on 2026-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
