# Generated by assistant on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[
                ('english', 'English'),
                ('math', 'Mathematics'),
                ('physics', 'Physics'),
                ('chemistry', 'Chemistry'),
                ('electronics', 'Electronics'),
                ('computer', 'Computer Science'),
                ('unknown', 'Unknown'),
            ], default='unknown', max_length=20),
        ),
    ]
