# Generated by Django 4.2.30 on 2026-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_add_electronics_computer_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('engineering mechanics', 'Engineering Mechanics'), ('engineering graphics', 'Engineering Graphics'), ('general engineering civil', 'General Engineering (Civil)'), ('general engineering mechanical', 'General Engineering (Mechanical)'), ('general engineering computer', 'General Engineering (Computer)'), ('general engineering electrical', 'General Engineering (Electrical)'), ('general engineering electronics', 'General Engineering (Electronics)'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
